language: ruby
rvm:
  - 1.8.7
script: "rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.0.0"
matrix:
  allow_failures:
    - rvm: 1.8.7
notifications:
  email: true
gemfile: Gemfile
